# Generated by Django 5.2.5 on 2026-01-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_weather_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='web_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
