# Generated by Django 5.2.5 on 2026-01-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_order_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_bid_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
